### ISSUE TITLE
undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by paulrobertlloyd** [chrislopresto/guard-scss-lint#2]
Hello!

Great to see that someone has taken it upon themselves to create a scss-lint Guard plugin; doing it via a shell script always felt a bit icky! However, I seem to have come across an issue. With the following in my Guardfile:

``` rb
guard :'scss-lint', :config => 'config/lint/scss.yml' do
  watch(%r{^source/.+\.scss})
end
```

I get the following error:

``` bash
23:42:15 - ERROR - Invalid Guardfile, original error is:
> [#] undefined method `each' for nil:NilClass
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/bundler/gems/guard-scss-lint-24a5656e679f/lib/guard/scss-lint.rb:26:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/plugin_util.rb:78:in `new'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/plugin_util.rb:78:in `initialize_plugin'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard.rb:179:in `add_plugin'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/dsl.rb:183:in `block in guard'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/dsl.rb:182:in `each'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/dsl.rb:182:in `guard'
    from /Users/paulrobertlloyd/Sites/paulrobertlloyd.com/Guardfile:21:in `_instance_eval_guardfile'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/guardfile/evaluator.rb:119:in `instance_eval'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/guardfile/evaluator.rb:119:in `_instance_eval_guardfile'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/guardfile/evaluator.rb:54:in `evaluate_guardfile'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/setuper.rb:148:in `evaluate_guardfile'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/setuper.rb:314:in `_load_guardfile'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/setuper.rb:65:in `setup'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/commander.rb:23:in `start'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/cli.rb:113:in `start'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/aruba_adapter.rb:32:in `execute'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/lib/guard/aruba_adapter.rb:19:in `execute!'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/gems/guard-2.8.1/bin/guard:11:in `<top (required)>'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/bin/guard:23:in `load'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/bin/guard:23:in `<main>'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
```

Have I set the `:config` option properly, or is something broken?

Thanks again,

Paul

**Comment by chrislopresto** [comment]
Hey @paulrobertlloyd.. just saw this. There were (at least) two problems. I just pushed fixes. 

I am now able to use your config in another project I'm working on. Let me know if it does the trick for you.

Thanks.

**Comment by paulrobertlloyd** [comment]
Great, thanks; will give it a try this evening and report back! Will you be pushing this plugin to rubygems soon?

**Comment by chrislopresto** [comment]
I had been meaning to document things a bit, but there's no reason not to have it up there. I just tagged and pushed v0.0.2.

**Comment by paulrobertlloyd** [comment]
Thanks for the quick turnaround! Tried the latest version this evening. I think this particular issue can be closed, but a number of new errors are occurring now :-( Strangely, they only occur when using this plugin; when I use scss-lint directly, everything works fine. Sorry!
