### ISSUE TITLE
NoMethodError: undefined method `bubbles?'

### ISSUE THREAD

**Issue by paulrobertlloyd** [chrislopresto/guard-scss-lint#3]
When using a Guardfile that includes guard-scss-lint, I get the following error:

``` bash
21:23:33 - ERROR - Guard::Sass failed to achieve its <run_on_changes>, exception was:
> [#] NoMethodError: undefined method `bubbles?' for #33dd88
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/check_nesting.rb:161:in `transparent_parent?'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/check_nesting.rb:43:in `visit_children'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:38:in `visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:52:in `map'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:52:in `visit_children'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/check_nesting.rb:49:in `visit_children'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:38:in `visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:52:in `map'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:52:in `visit_children'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/check_nesting.rb:49:in `visit_children'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:36:in `block in visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/check_nesting.rb:57:in `visit_root'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:36:in `visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:24:in `visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/perform.rb:314:in `block in visit_import'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/stack.rb:88:in `block in with_import'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/stack.rb:115:in `with_frame'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/stack.rb:88:in `with_import'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/perform.rb:312:in `visit_import'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:36:in `visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/stack.rb:79:in `block in with_base'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/stack.rb:115:in `with_frame'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/stack.rb:79:in `with_base'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/perform.rb:158:in `visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:52:in `map'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:52:in `visit_children'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:36:in `block in visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/base.rb:36:in `visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/perform.rb:157:in `visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/visitors/perform.rb:8:in `visit'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/root_node.rb:36:in `css_tree'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/tree/root_node.rb:20:in `render'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/sass-3.4.7/lib/sass/engine.rb:268:in `render'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-sass-1.6.0/lib/guard/sass/runner.rb:83:in `compile'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-sass-1.6.0/lib/guard/sass/runner.rb:51:in `block (2 levels) in compile_files'
> [#] /Users/plloyd/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-sass-1.6.0/lib/guard/sass/runner.rb:50:in `block in compile_files'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-sass-1.6.0/lib/guard/sass/runner.rb:47:in `each'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-sass-1.6.0/lib/guard/sass/runner.rb:47:in `compile_files'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-sass-1.6.0/lib/guard/sass/runner.rb:23:in `run'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-sass-1.6.0/lib/guard/sass.rb:149:in `run_on_changes'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-sass-1.6.0/lib/guard/sass.rb:98:in `run_all'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-sass-1.6.0/lib/guard/sass.rb:133:in `run_with_partials'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-sass-1.6.0/lib/guard/sass.rb:147:in `run_on_changes'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:77:in `block in _supervise'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:74:in `catch'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:74:in `_supervise'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:57:in `block (2 levels) in run_on_changes'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:51:in `each'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:51:in `block in run_on_changes'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:135:in `block (3 levels) in _scoped_plugins'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:133:in `each'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:133:in `block (2 levels) in _scoped_plugins'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:132:in `catch'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:132:in `block in _scoped_plugins'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:129:in `each'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:129:in `_scoped_plugins'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/runner.rb:48:in `run_on_changes'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/setuper.rb:212:in `_process_queue'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/commander.rb:34:in `start'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/cli.rb:113:in `start'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/aruba_adapter.rb:32:in `execute'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/guard-2.8.2/bin/guard:11:in `<top (required)>'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/bin/guard:23:in `load'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/bin/guard:23:in `<main>'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
> [#] /Users/plloyd/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

This relates to the first variable listed in this file: https://github.com/paulrobertlloyd/paulrobertlloyd.com/blob/master/source/_stylesheets/helpers/_vars.scss

If I remove that variable, it will throw an error on the next. I suspect the same error will be caused by variables existing in other files also (hard to check, due to the existence of a separate nesting error being generated).

Invoking scss-lint via the shell (or via guard-shell) does not cause this error.
Invoking sass via the shell does not cause this error.

Any ideas?

**Comment by chrislopresto** [comment]
Interesting. If `scss-lint` works directly then the issues are hopefully `Config`-related.

We're obviously in need of tests. I'm juggling a lot this week, but I'll look at your project and attempt to reproduce the problems ASAP.

**Comment by chrislopresto** [comment]
@paulrobertlloyd Would you mind updating to v0.0.3 and trying again? We're now targeting the latest scss-lint version. Thanks.

**Comment by paulrobertlloyd** [comment]
No such luck, sadly. The same behaviour is exhibited. Even if a config file is not supplied, or the config file provides default values, the error is the same.
